//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tessin.Bladerunner
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class Icons
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"Tessin.Bladerunner.Icons",
#if NET40
				typeof(Icons).Assembly
#else
				typeof(Icons).GetTypeInfo().Assembly
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/account-circle.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string AccountCircle
		{
			get { return GetString("AccountCircle"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/air-horn.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string AirHorn
		{
			get { return GetString("AirHorn"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/alert.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Alert
		{
			get { return GetString("Alert"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/alert-circle.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string AlertCircle
		{
			get { return GetString("AlertCircle"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/alien-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string AlienOutline
		{
			get { return GetString("AlienOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/all-inclusive.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string AlIinclusive
		{
			get { return GetString("AlIinclusive"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/alphabetical-variant.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string AlphabeticalVariant
		{
			get { return GetString("AlphabeticalVariant"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/android-debug-bridge.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string AndroidDebugBridge
		{
			get { return GetString("AndroidDebugBridge"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/application.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Application
		{
			get { return GetString("Application"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/arrow-down.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ArrowDown
		{
			get { return GetString("ArrowDown"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/arrow-left.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ArrowLeft
		{
			get { return GetString("ArrowLeft"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/arrow-right.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ArrowRight
		{
			get { return GetString("ArrowRight"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/arrow-up.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ArrowUp
		{
			get { return GetString("ArrowUp"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/at.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string At
		{
			get { return GetString("At"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/atom.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Atom
		{
			get { return GetString("Atom"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bell-ring.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string BellRing
		{
			get { return GetString("BellRing"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bike.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Bike
		{
			get { return GetString("Bike"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bird.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Bird
		{
			get { return GetString("Bird"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bookmark.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Bookmark
		{
			get { return GetString("Bookmark"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bookmark-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string BookmarkOutline
		{
			get { return GetString("BookmarkOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bookmark-plus.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string BookmarkPlus
		{
			get { return GetString("BookmarkPlus"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bug-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string BugOutline
		{
			get { return GetString("BugOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/bus-school.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string BusSchool
		{
			get { return GetString("BusSchool"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/calendar-range.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string CalendarRange
		{
			get { return GetString("CalendarRange"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/cash-multiple.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string CashMultiple
		{
			get { return GetString("CashMultiple"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/chart-line.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ChartLine
		{
			get { return GetString("ChartLine"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/check-bold.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string CheckBold
		{
			get { return GetString("CheckBold"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/chevron-right.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ChevronRight
		{
			get { return GetString("ChevronRight"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/clock-time-four-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ClockTimeFourOutline
		{
			get { return GetString("ClockTimeFourOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/close.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Close
		{
			get { return GetString("Close"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/close-octagon.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string CloseOctagon
		{
			get { return GetString("CloseOctagon"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/code-braces.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string CodeBraces
		{
			get { return GetString("CodeBraces"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/coffee-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string CoffeeOutline
		{
			get { return GetString("CoffeeOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/cogs.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Cogs
		{
			get { return GetString("Cogs"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/content-copy.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ContentCopy
		{
			get { return GetString("ContentCopy"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/content-paste.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ContentPaste
		{
			get { return GetString("ContentPaste"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/content-save-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ContentSaveOutline
		{
			get { return GetString("ContentSaveOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/database.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Database
		{
			get { return GetString("Database"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/delete.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Delete
		{
			get { return GetString("Delete"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/dots-horizontal.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string DotsHorizontal
		{
			get { return GetString("DotsHorizontal"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/dots-vertical.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string DotsVertical
		{
			get { return GetString("DotsVertical"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/download.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Download
		{
			get { return GetString("Download"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/download-circle.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string DownloadCircle
		{
			get { return GetString("DownloadCircle"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/duck.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Duck
		{
			get { return GetString("Duck"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/egg-easter.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string EggEaster
		{
			get { return GetString("EggEaster"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/email-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string EmailOutline
		{
			get { return GetString("EmailOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/eye.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Eye
		{
			get { return GetString("Eye"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/eye-off.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string EyeOff
		{
			get { return GetString("EyeOff"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/file.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string File
		{
			get { return GetString("File"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/filter.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Filter
		{
			get { return GetString("Filter"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/filter-menu.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string FilterMenu
		{
			get { return GetString("FilterMenu"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/folder.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Folder
		{
			get { return GetString("Folder"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/folder-open.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string FolderOpen
		{
			get { return GetString("FolderOpen"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/folder-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string FolderOutline
		{
			get { return GetString("FolderOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/folder-plus-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string FolderPlusOutline
		{
			get { return GetString("FolderPlusOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/hammer-screwdriver.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string HammerScrewdriver
		{
			get { return GetString("HammerScrewdriver"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/help-circle-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string HelpCircleOutline
		{
			get { return GetString("HelpCircleOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/lightning-bolt.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string LightningBolt
		{
			get { return GetString("LightningBolt"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/login.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Login
		{
			get { return GetString("Login"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/logout.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Logout
		{
			get { return GetString("Logout"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/magnify.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Magnify
		{
			get { return GetString("Magnify"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/magnify-plus.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string MagnifyPlus
		{
			get { return GetString("MagnifyPlus"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/message-bulleted.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string MessageBulleted
		{
			get { return GetString("MessageBulleted"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/message-reply.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string MessageReply
		{
			get { return GetString("MessageReply"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/pencil.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Pencil
		{
			get { return GetString("Pencil"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/pencil-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string PencilOutline
		{
			get { return GetString("PencilOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/plus.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Plus
		{
			get { return GetString("Plus"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/plus-circle.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string PlusCircle
		{
			get { return GetString("PlusCircle"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/plus-circle-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string PlusCircleOutline
		{
			get { return GetString("PlusCircleOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/plus-thick.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string PlusThick
		{
			get { return GetString("PlusThick"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/power.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Power
		{
			get { return GetString("Power"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/refresh.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Refresh
		{
			get { return GetString("Refresh"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/send.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Send
		{
			get { return GetString("Send"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/sitemap.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Sitemap
		{
			get { return GetString("Sitemap"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/star.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Star
		{
			get { return GetString("Star"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/star-circle.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string StarCircle
		{
			get { return GetString("StarCircle"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/star-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string StarOutline
		{
			get { return GetString("StarOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/surfing.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Surfing
		{
			get { return GetString("Surfing"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/table-large.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string TableLarge
		{
			get { return GetString("TableLarge"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/tag-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string TagOutline
		{
			get { return GetString("TagOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/thumb-up.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string ThumbUp
		{
			get { return GetString("ThumbUp"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/tooltip-text-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string TooltipTextOutline
		{
			get { return GetString("TooltipTextOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/translate.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Translate
		{
			get { return GetString("Translate"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/tune.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Tune
		{
			get { return GetString("Tune"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/upload-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string UploadOutline
		{
			get { return GetString("UploadOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/virus-outline.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string VirusOutline
		{
			get { return GetString("VirusOutline"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/web.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Web
		{
			get { return GetString("Web"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Icons/xml.svg;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Xml
		{
			get { return GetString("Xml"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}