//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tessin.Bladerunner
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class Javascript
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"Tessin.Bladerunner.Javascript",
#if NET40
				typeof(Javascript).Assembly
#else
				typeof(Javascript).GetTypeInfo().Assembly
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Javascript/Blades.js;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Blades
		{
			get { return GetString("Blades"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Javascript/NumberBox.js;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string NumberBox
		{
			get { return GetString("NumberBox"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Javascript/Popover.js;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Popover
		{
			get { return GetString("Popover"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Javascript/Toaster.js;System.String, mscorlib, Version=4.0.0.0, Culture=neutral,..."
		/// </summary>
		public static string Toaster
		{
			get { return GetString("Toaster"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}