//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tessin.Bladerunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Javascript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Javascript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tessin.Bladerunner.Javascript", typeof(Javascript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopoverSetPosition = function (wrapperId, targetId) {
        ///    setTimeout(function () {
        ///        var wrapperNode = document.getElementById(wrapperId);
        ///        //var wrapperBb = wrapperNode.getBoundingClientRect();
        ///        var targetNode = document.getElementById(targetId);
        ///        var targetBb = targetNode.getBoundingClientRect();
        ///        if (!wrapperNode) return;
        ///        wrapperNode.style.left = targetBb.left + &quot;px&quot;;
        ///        wrapperNode.style.top = (targetBb.top + targetBb.height + 4) + &quot;px&quot;;
        ///        wr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Popover {
            get {
                return ResourceManager.GetString("Popover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToasterSetPosition = function (wrapperId, timeout) {
        ///    if (timeout &gt; 0) {
        ///        setTimeout(function () {
        ///            var wrapperNode = document.getElementById(wrapperId);
        ///            if (!wrapperNode) return;
        ///            wrapperNode.classList.add(&quot;toaster-fadeout&quot;);
        ///        }, timeout);
        ///    }
        ///}.
        /// </summary>
        internal static string Toaster {
            get {
                return ResourceManager.GetString("Toaster", resourceCulture);
            }
        }
    }
}
